init:
  - git config --global core.autocrlf true

image: Visual Studio 2017

before_build:
  - nuget restore

configuration:
 - Release
platform: Any CPU

artifacts:
 - path: src\whitespace\bin\release\whitespace.exe

deploy:
 - provider: GitHub
   description: release description
   auth_token:
     secure: 3OhlF7ddpR8oLicTBUqcdtu7UByrPCEDcYbbNbcsDbA7Kxx8rGP+pJMWBwG9zXy9
   artifact: whitespace.exe
   on:
     appveyor_repo_tag: true
