init:
  - git config --global core.autocrlf true

image: Visual Studio 2017

before_build:
  - nuget restore

configuration:
 - Release
platform: Any CPU

artifacts:
 - path: src\whitespace\bin\release\whitespace.exe

deploy:
 - provider: GitHub
   description: release description
   artifact: whitespace.exe
   on:
     branch: master
     appveyor_repo_tag: true
